### ISSUE TITLE
Überarbeitung von Textelementen wegen des Statistik-Panels

### ISSUE THREAD

**Issue by stefan-sander** [topicmaps-wuppertal/corona-praevention#2]
@helllth: hier die angekündigete Auflistung dazu, welche textlichen Änderungen an der **Corona-Präventionskarte** wegen der Einfügung des Statistik-Moduls erforderlich sind:

- [x] **Tooltipp auf der Schaltfläche zum Öffnen des Applikationsmenüs**: Statt bisher **Einstelllungen | Anleitung*jetzt besser  **Einstelllungen | Statistik | Anleitung**
- [x] **Top-Level-Überschrift des Applijationsmenüs**: Statt **Einstellungen und Kompaktanleitung** jetzt besser **Einstellungen, Statistik und Kompaktanleitung**
- [x] Der Platzhaltertext "Geben Sie einen Suchbegriff ein" ist noch nicht optimal. Wenn mn bei einem ganzen Satz bleibt und groß anfängt, muss man mit einem Punkt abschließen: "Geben Sie einen Suchbegriff ein." Alternativ könnte man mit einem Satzfragement arbeiten, z. B. "Suchbegriff eingeben" oder "bitte Suchbegriff eingeben". Oder man nimmt den Stil, den wir bisher verwendet haben "Stadtteil | Adresse | POI". Mein Favorit wäre die letzte Option.
- [x] Der einleitende Text oberhalb der Grafik im Panel "Statistik" muss noch überarbeitet werden. Die Überschriften können hier entfallen. Außerdem bezieht sich der 3. Satz im 1. Abschnitt auf Tabellen, die hier nicht angezeigt werden, er kann also ebenfalls entfallen. Mit ein paar stilistischen Verbesserungen verbleibt als Textbaustein:

Das folgende Diagramm wird stündlich automatisch an die beim Gesundheitsamt zur COVID-19-Epidemie erfassten Fallzahlen angepasst. Bewegen Sie den Mauszeiger auf eine der farbigen Säulen in der Grafik, um sich die jeweilige Fallzahl und das zugehörige Referenzdatum anzeigen zu lassen. Durch Anklicken der farbigen Punkte in der Legende unterhalb des Diagramms können Sie einzelne Rubriken aus- und wieder einblenden.

**Comment by helllth** [comment]
> * **Tooltipp auf der Schaltfläche zum Öffnen des Applikationsmenüs**: Statt bisher **Einstelllungen | Anleitung*jetzt besser  **Einstelllungen | Statistik | Anleitung**

<img width="296" alt="Screenshot 2021-03-16 at 11 01 29" src="https://user-images.githubusercontent.com/837211/111290966-fa4b3e80-8646-11eb-8e71-1d92c5101f70.png">

```html
 <TopicMapComponent
    ...
     applicationMenuTooltipString='Einstelllungen | Statistik | Anleitung'
    ...
/>

**Comment by helllth** [comment]
> * **Top-Level-Überschrift des Applijationsmenüs**: Statt **Einstellungen und Kompaktanleitung** jetzt besser **Einstellungen, Statistik und Kompaktanleitung**

<img width="587" alt="Screenshot 2021-03-16 at 11 02 59" src="https://user-images.githubusercontent.com/837211/111291192-3aaabc80-8647-11eb-8227-c635b742cb26.png">


```html
<DefaultAppMenu
      menuTitle='Einstellungen, Statistik und Kompaktanleitung'
     ...
```

**Comment by helllth** [comment]
@stefan-sander Rückfrage zur dem Text über der Statistik:

Soll die bisherige Struktur beibehalten werden (dein Text wurde aufgesplittet)?

<img width="1103" alt="Screenshot 2021-03-16 at 11 53 19" src="https://user-images.githubusercontent.com/837211/111297822-5cf40880-864e-11eb-9ab5-08b2205f6abe.png">

... oder soll nur ein Absatz dargestellt werden (genau wie spezifiziert)?

<img width="1096" alt="Screenshot 2021-03-16 at 11 54 56" src="https://user-images.githubusercontent.com/837211/111297967-8876f300-864e-11eb-80be-203f11da8cf4.png">

**Comment by helllth** [comment]
tel Abstimmung:

<img width="1112" alt="Screenshot 2021-03-16 at 12 01 35" src="https://user-images.githubusercontent.com/837211/111298721-603bc400-864f-11eb-920c-a9d011493858.png">

**Comment by helllth** [comment]
Durch Anklicken der farbigen Punkte in der Legende unterhalb des Diagramms können
                  Sie einzelne Rubriken aus- und wieder einblenden.

**Comment by helllth** [comment]
:ship:

**Comment by stefan-sander** [comment]
Mir ist noch aufgefallen, dass die fetten Begriffe **Einstellungen**, **Statistik** und **Kompaktanleitung** im einleitenden Textabschnitte nicht als Hyperlink auf das jeweilige Panel des Applikationsmenüs angelegt sind. Das sollte noch nachgeholt werden.

**Comment by helllth** [comment]
Um es möglichst einfach zu halten und ein schnelles Ergebnis zu liefern, habe ich das Menu der Generic Topic Map verwendet, welche als Introduction nur einen Markdown String zulässt. Wenn ich die gewünschten Änderungen trotzdem machen soll, wird es etwas komplexer. Wenn das gewünscht wird, einfach hier nochmal kommentieren oder das Issue schließen.

**Comment by stefan-sander** [comment]
Das ist tatsächlich hier eher nachrangig, ich schließe daher.
