### ISSUE TITLE
Kompaktanleitung > Datengrundlagen

### ISSUE THREAD

**Issue by helllth** [topicmaps-wuppertal/corona-praevention#5]
per Mail von @vzupan 

folgender Vorschlag für die Beschreibung der dargestellten Informationen innerhalb der Karte.
Dieser Abschnitt kann im unteren Bereich des Abschnitts Kompaktanleitung > Datengrundlagen eingebunden werden.

Zusätzlich zeigt die Corona-Präventionskarte eine Teilmenge des Datensatzes der Interessanten Orte Wuppertal (POI) [Verlinkung zum Open-Data-Portal] aus dem Open-Data-Angebot der Stadt Wuppertal. Die Teilmenge wird durch eine Filterung der POIs erzielt, welche in ihrer Bezeichnung den Begriff ‘Corona‘ enthalten.

**Comment by stefan-sander** [comment]
Die Publikation der Corona-Präventionsorte als Open-Data ist erfolgt. Wir können auf diesen Datensatz also jetztz direkt Bezug nehmen. Dass es sich um eine Filterung der POI-Daten handelt, ist in den Metadaten der Corona-Präventionsorte ausgeführt, das brauchen wir m. E. nicht in der Kompaktanleitung der TopicMap zu erläutern. Der modfizierte Textvorschlag wäre demnach:

Zusätzlich zeigt die Corona-Präventionskarte den Datensatz [Corona-Präventionsorte Wuppertal](https://offenedaten-wuppertal.de/dataset/corona-pr%C3%A4ventionsorte-wuppertal) aus dem Open-Data-Angebot der Stadt Wuppertal.

**Comment by stefan-sander** [comment]
@vzupan: Dann müssen wir uns noch überlegen, wo der Hinweis auf das Open-Data-Angebot platziert werden soll. Im Moment benutzt die Corona-Präventionskarte die Kompaktanleitungskonfiguration der GenericTopicMap. Dort ist ein individueller Text ausschließlich im Abschnitt "Hintergrund" vorgesehen. Wenn wir dabei bleiben, müssten wir den Hinweis also dort unterbringen. Im Moment steht dort ein Platzhalter, den @helllth aus dem Wuppertaler Internet-Auftritt zu den Testzentren extrahiert hat. 

Die Alternative wäre die Einführung eines zweiten konfigurierbaren Bereichs unterhalb der festen Bullet-Liste im Abschnitt Datengrundlagen. (Dort steht der Hinweis auf die verwendeten Open-Data-Fachdaten ja auch bei den meisten älteren TopicMaps.)

Ich bin unentschieden, vielleicht habe ich ein leichte Tendenz dazu, die Dinge hier so einfach wie möglich zu halten und bei der Spezialisierung des Abschnittes "Hintergrund" zu bleiben. Was meinst du?

**Comment by vzupan** [comment]
@stefan-sander: Der Vorschlag von oben ist noch nicht eingebunden.
> Zusätzlich zeigt die Corona-Präventionskarte eine Teilmenge des Datensatzes der Interessanten Orte Wuppertal (POI) [Verlinkung zum Open-Data-Portal] aus dem Open-Data-Angebot der Stadt Wuppertal. Die Teilmenge wird durch eine Filterung der POIs erzielt, welche in ihrer Bezeichnung den Begriff ‘Corona‘ enthalten.

**Comment by vzupan** [comment]
@stefan-sander: bei der Überlegung "wo" habe ich mich an der TopicMap Park+Ride-Karte orientiert
![image](https://user-images.githubusercontent.com/56924890/112325396-f1481600-8cb3-11eb-8c8f-208609eee3d0.png)

**Comment by stefan-sander** [comment]
Nach telefonsicher Abstimmung mit @vzupan: Wir halten die Kompaktanleitung hier so "simple as possible" und arbeiten mit nur einem individuellen Abschnitt, nämlich **Hintergrund**. Ich poste dazu gleich einen Textvorschlag, der auch den Verweis auf den verwendeten Open-Data-Datensatz enthalten wird.

**Comment by stefan-sander** [comment]
Hier der Vorschlag:

### Hintergrund ###

Ein kostenloser Corona-Schnelltest pro Woche - dieses Angebot richtet sich seit Mitte März 2021 an jede Bürgerin und jeden Bürger. Auch in Wuppertal entstehen immer mehr Schnelltestzentren. Die Corona-Präventionskarte bietet einen Überblick über die Testzentren und sonstige relevante Einrichtungen wie das Corona-Impfzentrum. Die Informationen zu diesen "Corona-Präventionsorten" werden zunächst vom Presseamt der Stadt Wuppertal auf der städtischen Homepage publiziert und von dort zeitnah vom Team "Stadtkartographie" in den Datensatz der [interessanten Orte](https://offenedaten-wuppertal.de/dataset/interessante-orte-poi-wuppertal) (Points of Interest, kurz POI) im Wuppertaler Stadtgebiet übernommen. Diese Daten sind die Grundlage für die Darstellung in der Corona-Präventionskarte. Sie sind auch im Open-Data-Angebot der Stadt Wuppertal im täglich automatisch aktualisierten Datensatz [Corona-Präventionsorte Wuppertal](https://offenedaten-wuppertal.de/dataset/corona-pr%C3%A4ventionsorte-wuppertal) verfügbar.

**Comment by helllth** [comment]
<img width="1098" alt="Screenshot 2021-03-24 at 23 42 46" src="https://user-images.githubusercontent.com/837211/112393015-aac9da00-8cfa-11eb-85f6-6802a45a20d9.png">

**Comment by helllth** [comment]
:ship:
