### ISSUE TITLE
Farbwahl der Signaturen

### ISSUE THREAD

**Issue by helllth** [topicmaps-wuppertal/corona-praevention#6]
Das Impfzentrum soll eine soll eine andere Farbe erhalten `#74000B`. Außerdem könnten wir die noch nicht aktiven Testzentren grau darstellen um dem Bürger einen besseren Überblick zu geben wo er sich testen lassen kann. Screenshot dazu folgt in Kürze.

**Comment by helllth** [comment]
Gefällt mir ganz gut:

<img width="1120" alt="Screenshot 2021-03-24 at 10 20 09" src="https://user-images.githubusercontent.com/837211/112285375-8b936400-8c8a-11eb-9bed-04e5a8513c39.png">

**Comment by stefan-sander** [comment]
Finde ich auch sehr gut.

**Comment by helllth** [comment]
Das Öffnungsdatum in der Klammer wird jetzt ausgewertet. Sieht man am selektierten Schnelltestzentrum:

<img width="1130" alt="Screenshot 2021-03-24 at 11 39 09" src="https://user-images.githubusercontent.com/837211/112296982-a0c1c000-8c95-11eb-91f7-eb8c68260594.png">

**Comment by helllth** [comment]
Gesamtbild:

<img width="1410" alt="Screenshot 2021-03-24 at 11 42 17" src="https://user-images.githubusercontent.com/837211/112297313-0746de00-8c96-11eb-890a-a1addf15b172.png">

**Comment by helllth** [comment]
:ship:

**Comment by helllth** [comment]
Evtl. ein Leeren des Caches notwendig
