### ISSUE TITLE
Rückfrage TopicMap-Verhalten in Browser-Historie

### ISSUE THREAD

**Issue by vzupan** [topicmaps-wuppertal/corona-praevention#7]
Folgendes Verhalten wurde von @sandra-simmert gemeldet, dieses kann ich reproduzieren.

Auf dieser Internetseite ist die Corona-Präventionskarte eingebettet:
https://www.wuppertal.de/rathaus-buergerservice/corona/corona-schnelltestzentren-ueberblick.php

Beim Betrachten der Karte und anschließendem Verschieben/Zoomen in der Karte, wird jede Aktion (aktuelle Kartenansicht) als Element in der Browser-Historie aufgeführt.
Dadurch führt der "Zurück-Button" des Browsers nicht zur vorherigen Internetseite, sondern zur vorherigen Kartenansicht in der TopicMap.
Die Einbettung der Online-B-Plan-Auskunft (https://www.wuppertal.de/bebauungsplaene) zeigt das gleiche Verhalten.

@helllth: ist dieses Verhalten so gewollt?

**Comment by helllth** [comment]
Yes. It is a feature :wink: 

Ein Featurerequest von Anfang an war, dass die Position/Zoomstufe der Karte in der URL auswirkt und umgekehrt. Bei einem iFrame manipuliert diese Änderung das `src` Attribut des iFrames, was wohl die History manipuliert.

Soll heißen: Ich habe nichts dazu gemacht, dass das so funktioniert, war aber trotzdem begeistert als ich es herausgefunden habe.
