### ISSUE TITLE
TM Corona: Vorschau in Einstellungsfenster

### ISSUE THREAD

**Issue by vzupan** [topicmaps-wuppertal/corona-praevention#8]
Die Kartenvorschau im Einstellungsfenster zeigt aktuell folgendes Bild:
![image](https://user-images.githubusercontent.com/56924890/128859061-09c79e78-0eba-475e-87ce-162cc036e1b6.png)

Der gewählte Maßstab scheint nicht passend zu sein.

**Comment by helllth** [comment]
ich schaue

**Comment by helllth** [comment]
geändert: 🔜 :ship: @ v0.9.5

**Comment by helllth** [comment]
<img width="1203" alt="Screenshot 2021-08-25 at 13 41 21" src="https://user-images.githubusercontent.com/837211/130784518-fa159140-2f32-457f-a299-1036f57d5b59.png">
