### ISSUE TITLE
TM Corona: Erweiterung der Fallunterscheidung für Einfärbung der Icons

### ISSUE THREAD

**Issue by vzupan** [topicmaps-wuppertal/corona-praevention#9]
Die Einfärbung der Icons in der Corona-Präventionskarte wird in der Datei "corona-praevention/src/App.js" ab Zeile 81 gesteuert.
Das Icon zum Wuppertaler Impfzentrum wurde bis zur Schließung in dunkelrot eingefärbt. 
Aktuell bestehen weitere Impfangebote, welche in Absprache mit dem Presseamt in die Corona-Präventionskarte eingepflegt wurden.
@birgit-metzner: Danke hierfür.

Diese "mobilen Impfangebote" sollen die gleiche Farbe enthalten wie das ursprüngliche Impfzentrum.

@helllth: die Fallunterscheidung für das Impfzentrum kann mit einem Oder-Statement erweitert werden, wobei der Begriff "mobiles impfangebot" im POI-Namen enthalten sein soll.

![image](https://user-images.githubusercontent.com/56924890/144055687-f68d280b-b2d9-4e9a-ae65-bfd6b3bb6542.png)

In diesem Kartenausschnitt befindet sich ein mobiles Impfangebot: https://topicmaps-wuppertal.github.io/corona-praevention/#/?lat=51.271757747234545&lng=7.2002506256103525&title&zoom=18.

**Comment by helllth** [comment]
<img width="1108" alt="Screenshot 2021-12-01 at 11 31 48" src="https://user-images.githubusercontent.com/837211/144218611-ccdd836d-3f2b-4986-843e-8181e3f6e08d.png">

:soon: :ship: @ v1.0.1
